# Generated by Django 5.0.3 on 2024-03-22 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_steps_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_r',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
